export default {
  BAD_REQUEST_ERROR: 400,
  UNAUTHORIZED_ERROR: 401,
  FORBIDDEN_ERROR: 403,
  NOT_FOUND_ERROR: 404,
  CONFLICT: 409,
  ROUTING_ERROR: 1,
  INVALID_TYPE_ERROR: 2,
  DATA_BASE_ERROR: 3,
  INVALID_PARAMS_ERROR: 4,
};
